### ISSUE TITLE
Binarios y hexadecimales (suma, resta y multiplicación)

### ISSUE THREAD

**Issue by Nelson295281** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Nelson295281#1]
[NELSON GRUPO 1AS N° DE CONTROL 24620235.pdf](https://github.com/user-attachments/files/16843673/NELSON.GRUPO.1AS.N.DE.CONTROL.24620235.pdf)

**Comment by UsuarioIncognito** [comment]
portada: 25
Procedimiento:15
Figuras, ilustraciones, fotografías: 25
Resultados y conclusiones: 25
Calificación de la práctica: 18
